name: CI

on:
  push:
    branches:
      - '**'  # Запуск на любые ветки
  pull_request:
    branches:
      - '**'  # Запуск на любые pull request ветки

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install --no-cache

    - name: Run tests
      run: |
        poetry run pytest
